// secure-config.js - Contains sensitive configuration
// This file should NOT be committed to version control
// Generated by setup-dev.js

const secureConfig = {
  "GEMINI_API_KEY": "AIzaSyA6aaZi9q4LR5cYFxeTBRDDoN5IFJjGXBU",
  "FIREBASE_CONFIG": {
    "apiKey": "AIzaSyBvyw7xWPtHqOyhATkAaKYvFh0ygbDREI4",
    "authDomain": "health-2edac.firebaseapp.com",
    "projectId": "health-2edac",
    "storageBucket": "health-2edac.firebasestorage.app",
    "messagingSenderId": "105804661408",
    "appId": "1:105804661408:web:5fbf7c890cb739f8faffc5"
  }
};

// Export for use in other files
window.secureConfig = secureConfig;
