#!/usr/bin/env node

/**
 * Development Setup Script
 * Generates secure-config.js from environment variables or .env file
 * Run with: node setup-dev.js
 */

const fs = require('fs');
const path = require('path');

function setupDevelopment() {
  console.log('🔧 Setting up Smart Health Assistant for development...\n');

  // Check if secure-config.js already exists
  const configPath = path.join(__dirname, 'js', 'secure-config.js');
  if (fs.existsSync(configPath)) {
    console.log('⚠️  secure-config.js already exists. Skipping generation.');
    console.log('   If you need to update it, delete the file and run this script again.\n');
    return;
  }

  // Try to load from .env file
  let envVars = {};
  const envPath = path.join(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    console.log('📄 Loading configuration from .env file...');
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
      const [key, value] = line.split('=');
      if (key && value) {
        envVars[key.trim()] = value.trim().replace(/['"]/g, '');
      }
    });
  } else {
    console.log('📄 No .env file found. Using placeholder values...');
    console.log('   Create a .env file or set environment variables manually.\n');
  }

  // Create secure-config.js
  const config = {
    GEMINI_API_KEY: envVars.GEMINI_API_KEY || process.env.GEMINI_API_KEY || "your_gemini_api_key_here",
    FIREBASE_CONFIG: {
      apiKey: envVars.FIREBASE_API_KEY || process.env.FIREBASE_API_KEY || "your_firebase_api_key",
      authDomain: envVars.FIREBASE_AUTH_DOMAIN || process.env.FIREBASE_AUTH_DOMAIN || "your_project.firebaseapp.com",
      projectId: envVars.FIREBASE_PROJECT_ID || process.env.FIREBASE_PROJECT_ID || "your_project_id",
      storageBucket: envVars.FIREBASE_STORAGE_BUCKET || process.env.FIREBASE_STORAGE_BUCKET || "your_project.appspot.com",
      messagingSenderId: envVars.FIREBASE_MESSAGING_SENDER_ID || process.env.FIREBASE_MESSAGING_SENDER_ID || "your_sender_id",
      appId: envVars.FIREBASE_APP_ID || process.env.FIREBASE_APP_ID || "your_app_id"
    }
  };

  const configContent = `// secure-config.js - Contains sensitive configuration
// This file should NOT be committed to version control
// Generated by setup-dev.js

const secureConfig = ${JSON.stringify(config, null, 2)};

// Export for use in other files
window.secureConfig = secureConfig;
`;

  fs.writeFileSync(configPath, configContent);
  console.log('✅ Created js/secure-config.js');
  console.log('⚠️  Remember: Never commit this file to version control!\n');

  // Check if all values are set
  const missing = [];
  if (config.GEMINI_API_KEY === "your_gemini_api_key_here") missing.push('GEMINI_API_KEY');
  if (config.FIREBASE_CONFIG.apiKey === "your_firebase_api_key") missing.push('FIREBASE_API_KEY');

  if (missing.length > 0) {
    console.log('⚠️  The following values need to be configured:');
    missing.forEach(key => console.log(`   - ${key}`));
    console.log('\n   Update your .env file or edit js/secure-config.js directly.\n');
  } else {
    console.log('🎉 Development setup complete! All configuration values are set.\n');
  }
}

if (require.main === module) {
  setupDevelopment();
}